/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chalmers.dat055.clocks;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import java.time.Clock;
import java.util.Date;
import java.util.concurrent.atomic.AtomicBoolean;

public class App extends Application {
    public static void main(String[] args) { launch(); }

    @Override
    public void start(Stage stage) throws Exception {
        var quit = new AtomicBoolean(false);
        stage.setOnCloseRequest((e) -> quit.set(true));

        var clockCET = new ClockView(144, 144) {
            @Override
            public double getWait() {
                return quit.get() ? -1 : 0.125;
            }

            @Override
            public double getTime() {
                return ((double) new Date().getTime()) / 1000.0;
            }
        };

        var yearClock = new ClockView(144, 144) {
            @Override
            public double getWait() {
                return quit.get() ? -1 : 1;
            }

            @Override
            public double getTime() {
                var now = (double) new Date().getTime();
                var remain = (now % 3.1536e10) / 3.1536e10;

                return remain * 43200.0;
            }
        };

        var box = new HBox(8, clockCET, yearClock);
        box.setAlignment(Pos.CENTER);
        stage.setScene(new Scene(box, 304, 156));
        clockCET.display();
        yearClock.display();

        stage.show();
    }
}
